//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FHSSystemRenameClient.SystemRenameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SystemRenameService.ISystemRenameService")]
    public interface ISystemRenameService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISystemRenameService/RenameComputer", ReplyAction="http://tempuri.org/ISystemRenameService/RenameComputerResponse")]
        bool RenameComputer(string Name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISystemRenameServiceChannel : FHSSystemRenameClient.SystemRenameService.ISystemRenameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SystemRenameServiceClient : System.ServiceModel.ClientBase<FHSSystemRenameClient.SystemRenameService.ISystemRenameService>, FHSSystemRenameClient.SystemRenameService.ISystemRenameService {
        
        public SystemRenameServiceClient() {
        }
        
        public SystemRenameServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SystemRenameServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemRenameServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SystemRenameServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool RenameComputer(string Name) {
            return base.Channel.RenameComputer(Name);
        }
    }
}
